### PR TITLE
Add Makefile to honor "make install" and "make remove"

### PR DESCRIPTION
**Pull request by ItchyBugReporter**
This is the Makefile requested in issue #14

### CODE REVIEW

**Comment by ItchyBugReporter** [comment]
Okay, so it looks like GitHub is doing something weird with my pull request (no surprise there, GitHub always seems to be full of bugs when I use it). The profile.d commit wasn't supposed to be part of this pull request, I was going to do that as a separate pull request in case you wanted merge of my changes without merging the other. Any suggestions?

I'll wait until this is figured out before I push the Makefile that installs the profile.d script. (I already have it committed locally, but the push can wait)

**Comment by ItchyBugReporter** [comment]
*sigh* It seems github is still appending all my commits to this pull request even though it shouldn't... Hopefully they'll chime in soon on how to fix that (I sent them a message asking for help).

If you decide to merge everything before they do, you should undo commit b6e70ca, which has README.md saying to install from my fork. Commit 005983d is the last one saying to install from your repo.

**Comment by ItchyBugReporter** [comment]
I got an email back from a GitHub rep saying that this "append every commit to a pull request regardless of whether or not that is the right thing to do" thing is the way it is intended to work and that I need to create separate branches to have separate pull requests. I can do that if you want, but It may be a bit of time before I can get around to it. Or, I can just comment on which commits from my fork to look at.

**Comment by hkbakke** [comment]
Hi. I got a bit lost with your issues. What is the status of this one? I can see you are doing some changes now and then. Do you feel it is ready to be merged?

**Comment by ItchyBugReporter** [comment]
It's ready, but I would recommend reviewing my repo first before merging. Because of GitHub's policy of appending all commits to a pull request regardless of whether or not that is the right thing to do, merging this pull request will get you more than just the make file. I've added a profile.d script, a sample bash.command-not-found-messages file, packaging scripts for RPM and dpkg distros, and a TODO note for myself to do a few more packaging scripts.

I can recreate my fork and do the branches thing suggested in my previous comment if that will make it easier for you to cherry-pick which changes you want, but it may take awhile to figure out how GitHub wants me to do it.

**Pull request closed without merging**
